version: '3'

services:
  collectif:
    depends_on:
      - mysql
    image: "wordpress"
    restart: always
    environment:
      VIRTUAL_HOST: collectif-disrupt.com,*.collectif-disrupt.com
      LETSENCRYPT_HOST: collectif-disrupt.com,*.collectif-disrupt.com
      LETSENCRYPT_EMAIL: contact@collectif-disrupt.com
    volumes:
      - /root/wordpress:/var/www/html:rw
  mysql:
    image: "mysql"
    restart: always
    volumes:
      - /root/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

networks:
    default:
       external:
        name: ${NETWORK}